import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./_components/navbar";
import { Toaster } from 'react-hot-toast';


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
      <Toaster position="bottom-center"/>
        <TRPCReactProvider>
          <Navbar/>
          {/* <div className="mt-[146px]"> */}

          {children}
          {/* </div> */}
          
          </TRPCReactProvider>
      </body>
    </html>
  );
}
